### PR TITLE
export module error for downstream usage

### PR DESCRIPTION
**Pull request by gregdhill**
Signed-off-by: Gregory Hill <gregorydhill@outlook.com>

### CODE REVIEW

**Comment by ascjones** [comment]
CI error with missing docs for these

**Review by ascjones — APPROVED** [review]
LGTM. 

P.S. preferably add commits instead of force pushing to make the changes easier to see.

**Comment by gregdhill** [comment]
> LGTM.
> 
> P.S. preferably add commits instead of force pushing to make the changes easier to see.

Noted, I thought it would be okay for this PR since there were not many changes but I will adopt your strategy going forward.

**Comment by ascjones** [comment]
Yes no problem for this PR at all just noting it here

**Pull request merged**
