### PR TITLE
Add support for sudo

### LINKED ISSUE #112: module_with_calls is not public caused I failed to compose two calls
Hi there,

This issue might be quite the same with [How could I send a sudo call](https://github.com/paritytech/substrate-subxt/issues/84). 

I'm using subxt-0.6, which works fast and as expected. But I find out that this interface [module_with_calls](https://github.com/paritytech/substrate-subxt/blob/master/src/metadata.rs#L92) become private while I try to upgrade to 0.7. Here is code sample with subxt-0.6
```rust
let proposal = client.metadata().module_with_calls("MyModule")
		.and_then(|module| module.call("my_call", my_call_args))
		.map_err(|_| crate::Error::SubxtError("failed to compose a sudo call"))?;
let call = Call::new("Sudo", "sudo", proposal);
```

So now I cannot upgrade subxt to 0.7 or higher, can that interface change to be public? Or maybe you can give me a better solution instead of changing that interface.

Thanks!

### PR DESCRIPTION
**Pull request by dvc94ch**
@Dengjianping Do you want to finish it? Test is still failing because `ensure_signed` doesn't accept transactions with root origin. Closes #112

### CODE REVIEW

**Comment by Dengjianping** [comment]
Sorry for trying this so late.

I ran your sudo example as well as my own, I got error like this:
```
Rpc(Request(Error { code: ServerError(1010), message: "Invalid Transaction", data: Some(String("BadProof")) }))
```
It looks there's problem on the signer.

**Comment by dvc94ch** [comment]
Have you tried `purge-chain --dev`?

**Comment by Dengjianping** [comment]
Yes, I purged the whole chain. By the way, current rev I'm using is kind of old, does older rev cause this problem? I see that subsxt is using rc2.

**Comment by dvc94ch** [comment]
@Dengjianping yes, that could definitely cause weird issues. I'm closing this PR for now.

**Pull request closed without merging**
