### PR TITLE
Upgrade to substrate rc4 release

### PR DESCRIPTION
**Pull request by ascjones**

### CODE REVIEW

**Comment by ascjones** [comment]
Oddly I get the following test failure on CI, but not locally:

```
thread 'tests::test_create_raw_payload' panicked at 'assertion failed: `(left == right)`
  left: `MultiSignature::Ed25519(6dca736b575203dc2be429517559b797d157b2d20fd84d2e020b1c730c9ff6ffd6eaa6a40e20d57ebc2d559b3f06ca00477285ef7db6db10cb00a40ea5a5d600)`,
 right: `MultiSignature::Ed25519(be05d545cbe318283fd6df621041dcda51c8675b3e79d4fe5e63822f7c01b36546d862e0e378d08a783d38f6efb13f574940465414067c0177d69f972af17f09)`', src/lib.rs:611:9
```

@dvc94ch any ideas? #130 does touch this but can't see how it would break it.

**Comment by dvc94ch** [comment]
I guess you could revert and push to this branch to see if it fixes it

**Comment by ascjones** [comment]
Good idea I'll try that

**Comment by dvc94ch** [comment]
So here's one issue:
```diff
diff --git a/src/lib.rs b/src/lib.rs
index ae28b40..bce4734 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -578,7 +578,7 @@ mod tests {
 
         // create raw payload with AccoundId and sign it
         let raw_payload = client
-            .create_unsigned(
+            .create_payload(
                 balances::TransferCall {
                     to: &dest,
                     amount: 10_000,
```
But since you had it before I expect there to be another one.

**Comment by ascjones** [comment]
Thanks that fixed it @dvc94ch

**Comment by dvc94ch** [comment]
Can you release a new version of the client too? 0.10.0 doesn't build with the client feature enabled...

**Pull request merged**
