### PR TITLE
Release v0.15

### LINKED ISSUE #247: Publish crates release with substrate 3.0 support
**Description**

The stable release of Substrate 3.0 was published a few weeks ago. It could be great to have a stable release of SubXt too.

### PR DESCRIPTION
**Pull request by ascjones**
Closes #247

### CODE REVIEW

**Review by niklasad1 — COMMENTED** [review]
I think we need to assign exact versions to `jsonrpsee`, not to break the build.

I plan to release a new version soon after https://github.com/paritytech/jsonrpsee/pull/243/files is merged which has breaking changes and future alpha releases might break it too.

**Comment by ascjones** [comment]
Thanks @niklasad1, I will hold this back until new `jsonrsee` released. Let me know.

**Comment by niklasad1** [comment]
If we can get in https://github.com/paritytech/substrate-subxt/pull/250 it should be good to go.

**Comment by ascjones** [comment]
Also need to get all tests passing in https://github.com/paritytech/substrate-subxt/pull/253

**Comment by dvdplm** [comment]
Looks like #250 is the only thing blocking this yes?

**Comment by ascjones** [comment]
Yeah, I'll check it again and merge it if it looks good

**Comment by ascjones** [comment]
Ready to go I think, just needs a :heavy_check_mark:

**Comment by shekohex** [comment]
@niklasad1 Can you approve and merge this PR? I guess it is now Ready!

**Review by niklasad1 — APPROVED** [review]

**Pull request merged**
