### PR TITLE
Substrate 2.0.0

### PR DESCRIPTION
**Pull request by ascjones**
Upgrades to substrate 2.0.0

### CODE REVIEW

**Comment by ascjones** [comment]
Duplicate of #173

**Comment by ascjones** [comment]
Closing in favour of #173

**Comment by dvc94ch** [comment]
Tests pass if you update the refcount type to u32. Can you finish it and create a release?

**Comment by dvc94ch** [comment]
```diff
diff --git a/src/frame/system.rs b/src/frame/system.rs
index 7c6db4d..b0cb80f 100644
--- a/src/frame/system.rs
+++ b/src/frame/system.rs
@@ -118,7 +118,7 @@ pub trait System {
 }
 
 /// Type used to encode the number of references an account has.
-pub type RefCount = u8;
+pub type RefCount = u32;
 
 /// Information of an account.
 #[derive(Clone, Debug, Eq, PartialEq, Default, Decode, Encode)]
```

**Comment by ascjones** [comment]
@dvdplm is doing it in #173

**Comment by dvc94ch** [comment]
But this pr is finished with a one line change, the other is a draft

**Pull request closed without merging**
