### PR TITLE
Add Balances Locks

### PR DESCRIPTION
**Pull request by liuchengxu**

### CODE REVIEW

**Comment by liuchengxu** [comment]
Ping @ascjones

**Review by ascjones — COMMENTED** [review]
Thanks for this. Could you add a simple test? See the tests module at the bottom of the file.

**Comment by liuchengxu** [comment]
@ascjones Test added, and added `BondCall` for writing this test:(, I have run the tests successfully locally.

**Review by ascjones — APPROVED** [review]
If you merge master now it should fix the CI and we can get this merged

**Pull request merged**
